### PR TITLE
Prepare package to release on pypi

### PR DESCRIPTION
**Pull request by petrus-v**
Hi,

I'm Pierre, currently following the "INTRU" trainee from HSC!

Here I've prepare the minimum requirement to do the first release on [pypi](https://pypi.pyhon.org)

The intent is make easier the installation to be able to install patator
using pip.

Also I'm adding a section to tell how to install patator on a fresh Kali install (with deb package dependencies)

(notice that using console_scripts entry point that create binaries ready to run when installing the package, I'm not sure how you install the environment today)

### CODE REVIEW

**Comment by lanjelot** [comment]
Thanks for starting this. Couple of questions:
* Why do we now need the .gitignore and MANIFEST.in files? Are these needed for pypi/setup.py?
* I'm not too sure about the main() function you've added because it may break the multiprocessing.freeze_support() call which is required when compiling patator into a Windows binary. Any chance you could create the symlinks shortcuts without creating a main()?
* Why did you bump pycurl's version number to 7.43.0? Is it because that is the oldest version available via pip?

Cheers,
Seb

**Comment by petrus-v** [comment]
Hi,

Before answer I would apologies I had not seen yesterday the effort to create a debian package wich contains all requirements! We may mention it

* ``.gitignore`` is a facility to avoid commit unwanted files (this list is a quite usual python project list) some of those directory or files are generated while releasing a python package. Do you want me to remove it ?
* [MANIFEST.in](https://packaging.python.org/tutorials/distributing-packages/#manifest-in) is used to manage files we wants in the distribution that are not added [by default](https://docs.python.org/3.4/distutils/sourcedist.html#specifying-the-files-to-distribute). Reading the documentation *.md doesn't looks like distributed files. As long this files is not required I can remove it if you prefer ?
* Not sure to understand all your windows stuff, does the last commit [f35b0a3](https://github.com/lanjelot/patator/pull/76/commits/f35b0a3a3ddcee3d1a178fd705d4c238e8781b7f) has any chance to make it compatible with it ?
* pycurl:
   - version 7.43.0 (after playing with my apt show I m currently in the train with a small connectivity) appear to be the one installed with de deb package
  - Some of constant used in the code (at least this one ``pycurl.PROXYTYPE_SOCKS4A,`) are not present in version 7.19.3.

By the way, this is another issue but try/catching the pycurl import is useless as long we are using pycurl directly while setting up constants:

```python
  proxytype_mapping = {
    'http': pycurl.PROXYTYPE_HTTP,
    'socks4': pycurl.PROXYTYPE_SOCKS4,
    'socks4a': pycurl.PROXYTYPE_SOCKS4A,
    'socks5': pycurl.PROXYTYPE_SOCKS5,
    'socks5_with_hostname': pycurl.PROXYTYPE_SOCKS5_HOSTNAME,
  }
```

* while writting those lines I've push another commit regarding deb package
* I'll test the release and test it in a new env and will let you know if it works before merging this branch

regards,

**Comment by lanjelot** [comment]
Thanks mate, i'll be able to look into this in a few weeks. Again thank you for making a real effort to starting this, even though this issue was raised before (e.g. #31 and #65), you're the first one to act as a hacker and contribute some work. Cheers

**Comment by petrus-v** [comment]
oh! I had not seen those issues!

I've tested to create the package and install it in another virtualenv, I had to move patator in a subdirectory as [recommends](https://packaging.python.org/tutorials/distributing-packages/#your-package) even it's not required I believe tools like find_packages() expect it. So I let a patator.py in the root directory for compatibiliy with existing stuff. Do you wan't me to add a deprecated message to warn users to stop using that directly before completly removing that file later ?

**Comment by lanjelot** [comment]
Haven't forgotten about this, currently working on it. It's just taking longer than expected because I'm taking this opportunity to finally upgrade Patator to Python3. Cheers

**Comment by petrus-v** [comment]
great thanks and good news!

Now this PR is merged I was thinking to add travis (or an other) configuration to make sure installation work well and and some unit test.

Also I was wondering what you mind about splitting this huge python module (file: patator.py) ?

**Comment by lanjelot** [comment]
Hey buddy, first of all this PR is not merged yet and probably won't ever be as I am working on the pypi package myself. But again thanks heaps for kicking this off.

Second, i'm not too familiar with travis, I'm more familiar with ansible or vagrant. And I've actually started a Vagrantfile so it will probably end up next patator.py when I'm done.

Lastly, I'm not too keen on splitting patator.py into smaller files, but feel free to have a go and convince me otherwise.

Cheers

**Comment by petrus-v** [comment]
Yeah, I've seen the PR is not merged!

[Travis-ci](https://travis-ci.org/) is a famous online service that build and test application (that have unit-test). It's pretty good CI tool to help your community to contribute as it will test any PR. Of course you can also do more things like ensuring code formating  follow [PEP8](https://www.python.org/dev/peps/pep-0008/) or your own style guides, add coverage tool to know which part of the code is test or not.

I believe with this kind of tools re-factor are easier to do.

My 2cts!

**Comment by lanjelot** [comment]
It'd be good to have unit tests for Patator. I was thinking we could have a VagrantFile that spawns services to test Patator against for example. But I won't be working on that, I have other priorities at the moment.

Anyways, I pushed some code and the new 0.7 version, which is now available on pypi.

Feel free to test it out and to let me know if there's any more changes to be made.

Cheers

**Pull request closed without merging**
