### PR TITLE
Added RDP Gateway support

### PR DESCRIPTION
**Pull request by alexeypetrenko**
Had to suppress certain exceptions in pycurl due to RDP Gateway not closing HTTP connection.

### CODE REVIEW

**Comment by alexeypetrenko** [comment]
I'm not entirely sure what to put in dependencies. It seems that `uuid` is a standard python module, so it's not clear what to write there.
Currently there is this entry `'uuid': [('rdp_gateway',), '', ''],`

**Comment by lanjelot** [comment]
Thanks for a great PR.

Can you remove the check for uuid? It is unnecessary as it comes with Python 2.5.

What is the `timeout=1` you are passing in the usage example? Did you mean to pass `--timeout 1` instead? Please fix.

I'm not a big fan or the try/catch around perform_fp(), is it really necessary?

**Comment by alexeypetrenko** [comment]
Removed uuid import check.

---

`timeout` option is from `HTTP_fuzz`, which `RDP_gateway` inherits from.

The problem is that RDP Gateway doesn't close a connection if we guessed credentials correctly.:

```
curl -v https://server/remoteDesktopGateway/ -X  RDG_OUT_DATA -H "RDG-Connection-Id: {b28a3fb6-fd46-448a-b2f9-822cbcc60866}" --user "user:correctPass" --basic
* Server auth using Basic with user 'user'
> RDG_OUT_DATA /remoteDesktopGateway/ HTTP/1.1
> Host: server
> Authorization: Basic dXNlcjpjb3JyZWN0UGFzcw==
> User-Agent: curl/7.43.0
> Accept: */*
> RDG-Connection-Id: {b28a3fb6-fd46-448a-b2f9-822cbcc60866}
> 
< HTTP/1.1 200 OK
< Server: Microsoft-HTTPAPI/2.0
< Date: Wed, 26 Jul 2017 05:46:40 GMT
* no chunk, no close, no size. Assume close to signal end
< 

```

In this case `pycurl`  throws following exception:

```
<class 'pycurl.error'> (28, 'Operation timed out after 20001 milliseconds with 10 bytes received')
```
And it happens only when `pycurl.TIMEOUT` is expired. That's why I had to set timeout to a small value.

We could handle this exception in `execute` of `RDP_gateway` and do not change anything in `HTTP_fuzz`. However, in this case data received over HTTP is not available to the caller and we could only hope that it was `200` and not something else.

**Comment by alexeypetrenko** [comment]
Oops, didn't meant to close it.

**Comment by lanjelot** [comment]
Cool I see what you mean. You need to handle this RDPGateway-specific exception inside the `RDP_gateway` module then, as this is how things should be by design. What you could do maybe is make `perform_fp()` a class method so that you can overload it inside `RDP_gateway`. Or maybe you'll figure something out even cleaner while coding. Good luck :)

**Comment by alexeypetrenko** [comment]
I see you noticed my little activity here 😀.

Regarding `RDG-Connection-Id`: experiments show that it is crucial to use a new one after every successful atuthentication. Otherwise empty reply is returned to every subsequent attempt which uses the same id. So, I simply use a new one for every request. 

Your code works like a charm. It's really clever of you to use `HEAD` behaviour of curl instead of waiting for a timeout. Thanks for improving my code!

**Pull request closed without merging**
